### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to VeryDangerousNether v2.0.0

### ISSUE THREAD

**Issue by sherwood2142** [mVabo/VeryDangerousNether#2]
The server is running on PaperSpigot 1.15.2, Java 8. The plugin spams this error:

[13:47:30 ERROR]: Could not pass event AsyncPlayerChatEvent to VeryDangerousNether v2.0.0
java.lang.NoSuchFieldError: BASALT_DELTAS
        at verydangerousnether.verydangerousnether.nether.netherListeners.ChatEditing.isInNether(ChatEditing.java:45) ~[?:?]
        at verydangerousnether.verydangerousnether.nether.netherListeners.ChatEditing.onChat(ChatEditing.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-387]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1782) ~[?:git-Paper-387]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1697) ~[?:git-Paper-387]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-387]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]

**Comment by mVabo** [comment]
Hello, this is because versions post 2.x.x is only meant for 1.16.x. VDN Version 1.x.x works with 1.15.2 which is the version you use 👍
